### ISSUE TITLE
crashing consistently when buying directors cut voucher

### ISSUE THREAD

**Issue by alex-w-k** [Steamodded/smods#55]
just updated to latest today, and now seeing crashes after buying voucher in a run 
<img width="1179" alt="Screenshot 2024-03-28 at 11 41 56 AM" src="https://github.com/Steamopollys/Steamodded/assets/5731483/5c09865c-3dc8-4973-88b8-926b15d6db03">

**Comment by alex-w-k** [comment]
checking out specifically [0.8.2](https://github.com/Steamopollys/Steamodded/releases/tag/0.8.2) appears to fix the issue

**Comment by Aurelius7309** [comment]
I assume this is with the current repository state? We're preparing for a new release, and it seems this has gone unnoticed so far. Thanks for reporting, I will fix this before the new release goes live

**Comment by alex-w-k** [comment]
yep, updated to current, and reapplied, saw this crash and reverted back to specifically 0.8.2 and it appears to have been solved

**Comment by Aurelius7309** [comment]
"solved" is the wrong description here, because 0.8.2 is an earlier version than current. I've found the problem though and am deploying a fix.
